version: '3'
services:

  frontend:
    build:
      context: ./../frontend
      dockerfile: ./../frontend/frontend.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BACKEND_API_URL: "http://shortener-service:8080"
      AUTH_API_URL: "http://auth-service:8080"


  shortener-service:
    build:
      context: ./../shortener-service
      dockerfile: ./../shortener-service/shortener-service.dockerfile
    restart: always
    ports:
      - "9090:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=urls sslmode=disable timezone=UTC connect_timeout=5"

  auth-service:
    build:
      context: ./../auth-service
      dockerfile: ./../auth-service/auth-service.dockerfile
    restart: always
    ports:
      - "9091:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=urls sslmode=disable timezone=UTC connect_timeout=5"


  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urls
    volumes:
        - go-micro-urlshortener:/var/lib/postgresql/data/
volumes:
  # go-micro-mongo:
  #   external: true
  # go-micro-rabbitmq:
  #   external: true
  go-micro-urlshortener:
    external: true
