version: '3'
services:
  shortener-service:
    build:
      context: /home/vikash/go/src/github.com/vikas-gautam/go-micro-urlshortner/shortener-service
      dockerfile: /home/vikash/go/src/github.com/vikas-gautam/go-micro-urlshortner/shortener-service/shortener-service.dockerfile
    restart: always
    ports:
      - "9090:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=url sslmode=disable timezone=UTC connect_timeout=5"


  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url
    volumes:
        - go-micro-urlshortner:/var/lib/postgresql/data/
volumes:
  # go-micro-mongo:
  #   external: true
  # go-micro-rabbitmq:
  #   external: true
  go-micro-urlshortner:
    external: true
