version: '3'
services:
  shortener-service:
    build:
      context: /home/vikash/go/src/github.com/vikas-gautam/go-micro-urlshortner/shortener-service
      dockerfile: /home/vikash/go/src/github.com/vikas-gautam/go-micro-urlshortner/shortener-service/shortener-service.dockerfile
    restart: always
    ports:
      - "9090:8080"
    deploy:
      mode: replicated
      replicas: 1

#   postgres:
#     image: 'postgres:14.2'
#     ports:
#       - "5432:5432"
#     deploy:
#       mode: replicated
#       replicas: 1
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: users
#     volumes:
#         - go-micro-postgres:/var/lib/postgresql/data/
# volumes:
#   # go-micro-mongo:
#   #   external: true
#   # go-micro-rabbitmq:
#   #   external: true
#   go-micro-urlshortner-postgres:
#     external: true
